# Generated by Django 5.1.4 on 2025-01-08 18:58

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=255,
                unique=True,
                validators=[account.validators.validate_email],
            ),
        ),
    ]
