# Generated by Django 5.1.4 on 2025-01-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pasteapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paste",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="paste",
            name="password",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
